version: "3"

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      # - db_data:/var/lib/mysql
      - ./db_data:/var/lib/mysql

    restart: always
    # ports:
    #   - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    build: ./.docker/wordpress
    ports:
      - "8000:80"
    restart: always
    volumes:
      - "./wordpress:/var/www/html"
      - "./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
      # - "./xdebug:/var/logs/xdebug"

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      # XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000 remote_enable=1
      # XDEBUG_MODE: debug
      PHP_EXTENSION_XDEBUG: 1
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
